UPDATE
Module aiohttp is required

Traceback (most recent call last):
  File "/home/gdhindii/twayback/twayback.py", line 18, in <module>
    from aiohttp import ClientSession, TCPConnector
ModuleNotFoundError: No module named 'aiohttp'